###### Content below should go in automations.yaml
###### DO NOT COPY THESE INTO CONFIGURATION.YAML - create the automations in the UI then paste the code below in YAML mode

alias: .EVSE set MQTT MainsMeter from HA
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.meter_active_power_l1
    for:
      hours: 0
      minutes: 0
      seconds: 1
action:
  - service: mqtt.publish
    data_template:
      topic: SmartEVSE-XXXXX/Set/MainsMeter
      payload: |-
        {{
          ((states('sensor.meter_active_power_l1')|float / states('sensor.on_grid_l1_voltage')|float ) * (-1) * 10 ) | round(0) 
        }}:{{
          ((states('sensor.meter_active_power_l2')|float / states('sensor.on_grid_l2_voltage')|float )  * (-1) * 10 ) | round(0)
        }}:{{ 
          ((states('sensor.meter_active_power_l3')|float / states('sensor.on_grid_l3_voltage')|float )  * (-1) * 10 ) | round(0) 
        }}

## --------------------------------------------------------------

alias: .EVSE set MQTT HomeBatteryCurrent from HA
trigger:
  - platform: state
    entity_id:
      - sensor.battery_current
    for:
      hours: 0
      minutes: 0
      seconds: 1
action:
  - service: mqtt.publish
    data_template:
      topic: SmartEVSE-XXXXX/Set/HomeBatteryCurrent
      payload: "{{ (states('sensor.battery_current') | float * 10 * (-1)) | int }}"


